fullScreen();
println(displayWidth,displayHeight);
int appW = displayWidth;
int appH = displayHeight;
println("Var",appW,appH);
int paperW = 11;
int paperH = 16;
println(Math.PI);
float imagesongX = appW*2.5/paperW;
float imagesongY = appH*1.5/paperH;
float imagesongW = appW*6.5/paperW;
float imagesongH = appH*6.5/paperH;
rect(imagesongX,imagesongY,imagesongW,imagesongH);
/*
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
rect(X,Y,W,H);
*/
